name: ui_value
description: Simplify state management and reduce the need for multiple setState calls.
version: 1.0.0
repository: https://github.com/hacp0012/ui_value

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - ui
  - setstate
  - update
